print("Logical:  AND  (&&)")
print("False && False: " , False and False)
print("False && True: " , (False and True))
print("True && False: " , (False))
print("True && True: " , (True))
print("Logical: OR (||)")
print("False || False: " , False)
print("False || True: " , ( True))
print("True || False: " , (True))
print("True || True: " , (True))
print("Logical: NOT (!)")
print("!False: ", not False)
